"""
Task-6: работа с перменными окружения
"""

from airflow import DAG
from airflow.operators.bash import BashOperator

from datetime import timedelta, datetime
from textwrap import dedent

with DAG(
    'hw_i-vafin_6_dag',
    default_args={
        'depends_on_past': False,
        'email': ['airflow@example.com'],
        'email_on_failure': False,
        'email_on_retry': False,
        'retries': 1,
        'retry_delay': timedelta(minutes=5),  # timedelta из пакета datetime
    },
    description=__doc__,
    schedule_interval=timedelta(days=1),
    start_date=datetime(2023, 11, 22),
    tags=['hw_i-vafin'],
) as dag:
    dag.doc_md = __doc__

    for i in range(10):
        bash_task = BashOperator(
            task_id=f'bash_autogenerated_task_{i}',
            bash_command='echo $NUMBER',
            env={'NUMBER': i}
        )

    bash_task.doc_md = dedent(
        """\
    # Документация для задачи

    ## Название
    bash_autogenerated_task_{task_number}, где `{task_number}` - номер задачи, формируемый в **Airflow**

    ## Общее описание
    Задача выполняет _системную_ команду `echo`

    ## Особенности
    Airflow динамические создает 10 аналогичных задач, в каждую из которых, передает номер задачи (нумерация от 0 до 9)
    """
    )

    bash_task
